export const USERS_FETCHED = "USERS_FETCHED";
export const USER_SELECTED = "USER_SELECTED";
export const USER_RESET_SELECTED = "USER_RESET_SELECTED";
export const USERS_SET_NEXT = "USERS_SET_NEXT";
export const USERS_SET_PREVIOUS = "USERS_SET_PREVIOUS";
